[project]
name = "mdde2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.8",
    "jinja2>=3.1.5",
    "sqlmodel>=0.0.22",
    "uvicorn>=0.34.0",
]
